services:
  django_web:
    build: 
      context: ../app
      dockerfile: Dockerfile
    container_name: django_web
    env_file:
      - ../app/.env.prod
    ports:
    - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - django-web-with-jenkins
  nginx:
    image: nginx:alpine
    container_name: nginx_service
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django_web
    networks:
      - django-web-with-jenkins

volumes:
  jenkins_home:

networks:
  django-web-with-jenkins:
    driver: bridge